theme = "gruvbox"

[editor]
line-number = "relative"
rulers = [80]
shell = ["zsh", "-c"]
bufferline = "multiple"

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-D = ["extend_to_line_bounds", "yank", "paste_before"]
C-d = ["extend_to_line_bounds", "yank", "paste_after"]
esc = ["collapse_selection", "keep_primary_selection"]
